spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:cod3r-forum
    username: sa
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  boot:
    admin:
      client:
        url:
        - http://localhost:8081
  
   
forum:
  jwt:
    secret: rm!@N=Ke!~p8VTA2ZRK~nMDQX5Uvm!mD&]{@Vr?G;2?XhbC:Qa#9#eMLN\}x3?JR3.2zr~v)gYF^8\:8>:XfB:Ww75N/emt9Yj[bQMNCWwW\J?N,nvH.<2\.r~w]*e~vgak)X"v8H`MH/7"2E`,^k@n<vE-wD3g9JWPy;CrY*.Kd2_D])=><D?YhBaSua5hW%{2]_FVXzb9`8FH^b[X3jzVER&:jw2<=c38=>L/zBq`}C6tT*cCSVC^c]-L}&/
    expiration: 86400000
#Actuator
management:
  endpoints:        
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
info:
  app:
    name: "@project.name@"
    version: "@project.version@"
    groupId: "@project.groupId@"
    java:
      source: "@java.version@"
      target: "@java.version@"
 